# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\"I\n\nMsgRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\x12\n\x05money\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_money\"b\n\x0bMsgResponse\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x13\n\x06result\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x62\x61lance\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\t\n\x07_resultB\n\n\x08_balance2c\n\x06\x62ranch\x12*\n\x0bMsgDelivery\x12\x0b.MsgRequest\x1a\x0c.MsgResponse\"\x00\x12-\n\x0eMsgPropagation\x12\x0b.MsgRequest\x1a\x0c.MsgResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGREQUEST']._serialized_start=15
  _globals['_MSGREQUEST']._serialized_end=88
  _globals['_MSGRESPONSE']._serialized_start=90
  _globals['_MSGRESPONSE']._serialized_end=188
  _globals['_BRANCH']._serialized_start=190
  _globals['_BRANCH']._serialized_end=289
# @@protoc_insertion_point(module_scope)
